### ISSUE TITLE
Inwee breaks on Weechat 1.7

### ISSUE THREAD

**Issue by shymega** [susam/inwee#1]
As of Weechat 1.7 (more specifically, [this][wcmt] commit), the `%h/.weechat/weechat_fifo_{PID}` path no longer exists. In fact, it can now be custom defined by the user in the `fifo.conf` file.

My proposal to fix this is to try the PID version of the FIFO socket first, if that fails, fail **silently**, and then try the path `%h/.weechat/weechat_fifo`, and if that fails, then pass on a error message.

Inwee should also allow a parameter to accept a custom path to the FIFO socket.

Thanks!

[wcmt]: https://git.io/vMyfh

**Comment by susam** [comment]
@shymega Thanks for creating this issue. Due to my busy schedule, it is currently unknown to me when I may get time to fix this. If you would like to fix this yourself and if you have the time, please feel free to send me a pull request or a patch, and I will apply it to my repository and provide credit to you in the README.

**Comment by shymega** [comment]
I've opened a PR (#2) for this, as per your suggestion.
